// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'dart:io' show Platform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) {
      return android;
    } else if (Platform.isIOS) {
      return ios;
    } else {
      throw UnsupportedError(
        'DefaultFirebaseOptions are not supported for this platform.',
      );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB66YfV8dQGIwlAa3wxkCzC_SbJi974G7w',
    appId: '1:478220568403:android:1eb21ead9d5cc9240183a6',
    messagingSenderId: '478220568403',
    projectId: 'familycal-3b3a9',
    storageBucket: 'familycal-3b3a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdA5RUuB3T5a_x5Nb6Xg6Xg6Xg6Xg6Xg', // Placeholder - update if using iOS
    appId: '1:478220568403:ios:placeholder',
    messagingSenderId: '478220568403',
    projectId: 'familycal-3b3a9',
    storageBucket: 'familycal-3b3a9.firebasestorage.app',
    iosBundleId: 'com.example.familycal',
  );
}

